server:
  port: 8181
  servlet:
    context-path: /ui
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:data-mapper-identity;MODE=PostgreSQL
    username: sa
    password: